title: Applied Credit Risk
description: A collection of sources on recent advances and valuable research in the area of applied credit risk
markdown: kramdown
remote_theme: pages-themes/primer@v0.6.0
