title: Applied Credit Risk - Knowledge Base (Beta)
description: A collection of sources in the area of Credit Risk Management (Credit Risk Modeling, Governance) for practitioners and researchers
markdown: kramdown
remote_theme: jekyll/minima